### ISSUE TITLE
Multi-Field Validation

### ISSUE THREAD

**Issue by gizmoboy** [formly-js/angular-formly#109]
How would you suggest implementing a custom validator that spans multiple fields such that at least one of the fields must have a value?

For example, let's assume we have Wages, Pension, and Other income, and given that a user has indicated they have some income, we require a non-zero value in at least one of these fields.

**Comment by kentcdodds** [comment]
@gizmoboy, sorry this was never implemented. Do you still need this functionality?

**Comment by kentcdodds** [comment]
Closing this for now unless someone asks for this functionality again.

**Comment by 4ware** [comment]
Hi!

I would need this functionality to validate if either one of two inputs is set...

Thanks

**Comment by kentcdodds** [comment]
@4ware, you don't need to use a function to do that. You can easily do that using the string version of a [Formly Expression](http://docs.angular-formly.com/v6.10.1/docs/formly-expressions)

**Comment by 4ware** [comment]
Ah, i see. Thanks a lot!

**Comment by H3ll0W0rld** [comment]
Hi @kentcdodds.

Have you ever implemented "dangerouslyValidate" functionality in formly? 

We load fields configuration JSON via API server directly and need some complex validations like regex. Because we are trying to keep our code as dry as possible and will be having multiple configuration JSON files based on clients. It is not possible for us to add validation functions in our code.

I know I can't pass functions via JSON. It would be great if formly itself can do "eval" and execute validation functions.

Thank you for great framework and keep up the good work.

Kashyap

**Comment by kentcdodds** [comment]
Nothing like this was ever added and I don't expect it ever will be. If you need to do regex that's already possible via a pattern. See the Mac Address configuration in [this example](http://angular-formly.com/#/example/advanced/validators). Also, you can get pretty far with putting complex logic on the client and referencing that logic in your config using [fieldTransforms](http://angular-formly.com/#/example/very-advanced/field-transform).

Good luck.

**Comment by H3ll0W0rld** [comment]
Ok. I will try to do that. Thank you for your help.
