### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by k010** [formly-js/angular-formly#147]
Hi, first to all thanks is very usefull your module,
I've a question, has you consider to build the form element from JSON schema ???

**Comment by kentcdodds** [comment]
Thanks! I'm not sure what you're asking about. Are you talking about [json-schema.org](http://json-schema.org/)? I have no experience with that, but you're not the first to ask about this. #114 is about the same thing I believe. Could you explain what benefits we'd get from this. And how do you envision this being included?

**Comment by k010** [comment]
@kentcdodds thanks for response, i found a nice explication in this blog [json-schema-validation](http://www.asbjornenge.com/wwc/json_schema.html). 
Basically my idea is the same that @quietlyconfident In #114 mention. 
Don't worry about right now (i don't read before the #114) this is a suggest, and keep in mind this is a good idea implement in a future version. 

Nice work !

**Comment by quietlyconfident** [comment]
Chiming in on the utility of my (currently closed) feature request. . .

Angular-Formly takes in a JSON document (the Form Description Document or *FDD*) and uses it to render a form.  According to the documentation, validation is accomplished via a combination of Angular's built-in validation and the special validators object which contains validation functions.  Put differently, the "schema" for the data in a Formly form consists of the FDD, plus the built-in Angular validation directives, plus optionally the special validation functions in the "validators" object.

Changing this so that the FDD is a JSON Schema document has at least two benefits:

1. You  (the Formly maintainer(s)) can use other validators (like TV4) to do the validation and not write/maintain validation related code.
2. The JSON Schema document becomes the single-source-of-truth on the schema for the data structure.  The end-user could use the schema to validate the data in other places (e.g. on the server) without having to have a separate schema which is kept in sync with the Formly FDD.

This is the underlying approach taken by [Angular Schema Form](https://github.com/Textalk/angular-schema-form).

**Comment by kentcdodds** [comment]
Just to confirm, by

> You (the Formly maintainer(s)) can use other validators (like TV4) to do the validation and not write/maintain validation related code.

you're talking about use validating the field configuration to verify that it is correct? So we can warn the developer when they provide a config that is incorrect.

**Comment by quietlyconfident** [comment]
No, I think thats a different thing than what k010 is asking about here. (But I've proposed it in another issue.) I apologize, in advance and in a continuing fashion, for sowing confusion.  Discussions about schemas get very meta in a hurry and it is hard to keep track of what we're talking about :)

I think that what k010 is talking about in this thread is, the FDD should be a JSON Schema, so that you can validate the Data Model against it.  To make this more concrete, check out the [Formly Demo](http://formly-js.github.io/angular-formly/#!/).  On the left is the "Fields" pane which contains a JSON document which describes the form (i've taken to calling this the form description document or *FDD* but happy to use some other term if you'd like.)  Then on the right is the "Data Model" which is a JSON object.  If *Fields*/FDD was a JSON schema, then you could validate the data model against it with a [JSON Schema validator](https://json-schema-validator.herokuapp.com).  Thus using that JSON schema validator you could copy-and-paste the *Fields* JSON into the top pane, and the *Data* JSON into the bottom pane, and click the button, and it would tell you that the model was valid or not.

Or, a more useful real-world scenario. . . Perhaps your server-side application doesn't trust that your client side application will always give it good data.  So you want to validate the data in the browser as you enter it, but then when it hits the server you want to validate it again.  If the Fields/FDD is a JSON schema, then you can do that without having two separate documents which describe the data model (e.g. a server-side validation schema in some standard schema language PLUS the Formly "Fields" document on the client side).

**Comment by kentcdodds** [comment]
I apologize. I've never had any experience with JSON Schemas. So please understand if I just don't get it. But if I understand you correctly, you're saying that the FDD could validate the model which to me doesn't make any sense. The FDD describes the fields that represent the model. They do have a `validators` property, but that's a JavaScript/angular specific thing.

One thing that might make sense is to add a `schema` property to the field config that allows you to use a JSON Schema validator to validate the model. This would be in lieu of `validators` but would behave just like `validators` in that it would `$setValidity` for the `NgModelController` based on whether the schema validation passed. Would this be a good api to accomplish what you're talking about?

By the way, sorry I closed #114... I should have pursued it further or at least asked you before closing it.

**Comment by quietlyconfident** [comment]
Ha ha, thats ok.  When wing nuts such as myself from the internet start muddying up your project with crazy issues you're entitled to close them :)

But yeah, that is exactly right, the FDD *could* validate the data model and describe the form fields *if* it was a JSON schema.  Perhaps it would clarify to point out that per the [JSON Schema Spec](http://json-schema.org/latest/json-schema-core.html#anchor5) a JSON Schema may have properties that are not keywords.

Re: your proposal:
> One thing that might make sense is to add a schema property to the field config that allows you to use a JSON Schema validator to validate the model. This would be in lieu of validators but would behave just like validators in that it would $setValidity for the NgModelController based on whether the schema validation passed. Would this be a good api to accomplish what you're talking about?

Yes, I think that is a great idea.  If you add a schema property to the FDD, then you could validate the data model against the FDD.

My next thought is, if you did just that and stopped, there would be some redundancy between the schema property and the remainder of the FDD.  For example, consider just the First Name / Last Name fields of the Formly example.  Both the schema and the FDD would indicate the key, and the type, for example.  What the schema would not necessarily have is 'label', 'placeholder', and 'order'.  

But, if you added those *form description* properties to the schema (OK because, a schema may have properties that are not keywords), and we teach Formly how to read it, then rather than having a schema *inside* the form description, you have a schema which *is* the form description and also can be used directly to validate the document.

**Comment by kentcdodds** [comment]
This is very interesting. I think I'm finally getting it :laughing:

So, I'm thinking to enable this, we'd do something like this:

```javascript
angular.module('yourModule').config(function(formlyConfigProvider) {
  formlyConfigProvider.schemaValidator(function(data, schema) {
    var invalidValidators = validateSchema(data, schema);
    return !invalidValidators.length ? true : invalidValidators;
  });
});
```

Where `invalidValidators` would be something like:

```json
["required", "maxLength"]
```

And formly would take the `invalidValidators` and apply it to the `NgModelController` via `$setValidity` and you could use it with `ngMessages` like so:

```html
<div ng-messages="options.formControl.$error">
  <div ng-message="required">This field is required</div>
  <div ng-message="maxLength">Input too long</div>
</div>
```

Do you think this would be acceptable? Do you think that I'm missing anything?

**Comment by kentcdodds** [comment]
And of course that `validateSchema` function would likely call into [tv4](https://github.com/geraintluff/tv4) or something similar, but I don't want to include that library in formly. I'd like people to bring in whatever they'd like. Oh, and the `schemaValidator` function would be called anytime a field's model changed (based on a `$watch`). What do you think?

**Comment by kentcdodds** [comment]
Oh, and just to be clear. `schema` is the FDD for the field and data is the model for the field (this would be `field.model` `||` what is passed to `formly-form`). Would that work?

**Comment by k010** [comment]
@kentcdodds sorry for late response, i think sounds great for the first step to use a schema validation, then like comment @quietlyconfident, if you wanted, you can build certain properties in the form field, for eg. we get this simple schema: 

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "title": "Person",
    "properties": {
        "name": {
            "type": "string",
            "displayOrder": 0,
            "maxLength": 60,
            "defaultVisible": true,
            "title": "Name",
            "description": "Your name..."
        },        
        "lastname": {
            "type": "string",
            "displayOrder": 1,
            "maxLength": 30,
            "defaultVisible": true,
            "title": "Lastname",
            "description": "Your lastname"
        }
    },
    "required": ["name"]
}
```

And can build input properties base in the schema, you can take **type** and render the input type or get **title** and set the label or **description** and build the placeholder, etc...
 
Think it's posible implement something like this ?

**Comment by kentcdodds** [comment]
That's a significant departure from the current API. It's also a little more complicated api as well. The simplicity of `angular-formly` is one of its strong points. I don't think that we want to change the default api to do this...

However, I can definitely see the value. I think we may be able to detect that the given fields are a schema and generate the fields from the schema. So we'd do something like this:

```js
vm.model = { /* your model here */ };
vm.schema = { /* your schema here */ };
vm.fields = {}; // set just so we have reference to it in our javascript
```

```html
<formly-form model="vm.model" schema="vm.schema" fields="vm.fields"></formly-form>
```

Then, formly would generate the fields based on the schema and assign it to your `vm.fields` and it would invoke the `schemaValidator` function with the schema as described above any time the model changed.

I believe that the schema you recommended would be converted to something like this:

```js
[
  {
    key: 'name',
    data: {
    }
  }
]
```

Please note, this does not at all change formly's default api. It may also make things a little tricky to do anything creative if you do things this way. I'm also not promising that this would actually be possible. But I believe it should be.

**Comment by kentcdodds** [comment]
Sorry, that wasn't finished... Editing now.

**Comment by k010** [comment]
@kentcdodds would be great, add or not this feature thanks for the reply equal !!

**Comment by kentcdodds** [comment]
Would love help in the branch I started out. I'm not very familiar with this. I've pushed the 2.0.0 release anyway. We'll add this in a future version.

**Comment by yieme** [comment]
+1

**Comment by kentcdodds** [comment]
I think this should be part of a plugin, so I've created a new repo for that plugin. Anyone is welcome to implement it. https://github.com/formly-js/angular-formly-json-schema/issues/1
