### ISSUE TITLE
hide not working as expected when formdata is updated

### ISSUE THREAD

**Issue by skchi** [formly-js/angular-formly#148]
First of all, thanks for the great module.

But, i am having an issue, where i get the formdata from DB and build the forms based on it. I am able to build it perfectly, but the issue is i need to show some fields based on the values in the formdata.

Its works fine for the first time, but when i update the formdata, i still see the fields which needs to be hidden based on the condition.

I put down a plunker with the issue.

Initially i have a condition on text field to show/hide based on the type value, but when i change the formdata, it doesn't apply that condition any more.

http://plnkr.co/edit/Vrw3Qgd0SxHkeyDOjURa?p=preview

**Comment by kentcdodds** [comment]
First of all, you're very welcome :+1: Glad you've found it useful!

I'm not able to reproduce any issue whatsoever. No matter how much I change and move around, the field disappears when `type` is not equal to `1` which is the condition...

**Comment by skchi** [comment]
Thanks for the quick response, but i assume you are changing the type (select), instead if you change the "Form", you see the issue i am talking about.

**Comment by kentcdodds** [comment]
I'm changing everything I can. Here's what I see: http://cl.ly/3047330u1V19

**Comment by skchi** [comment]
Got what you are doing, but instead of changing the Type, if you just change the "forms", thats when i see the issue. I apologize if i am not clear.

If we select the form and then change the type field it does work.

Let me explain more.

If i have a form which has model with the data, where type = 1. 
eg: name field needs to shown. (I have a condition and it works fine), later i update the model data where type = 2, and the name needs to be hidden, in that scenario i still name field.

**Comment by kentcdodds** [comment]
So you're saying that when `form2` is selected, you want `type === 1` to show the text field and when `form1` is selected, you want `type === 2` to show the text field? I'm totally confused... What are you trying to accomplish?

**Comment by skchi** [comment]
here is the updated plunker ...

http://plnkr.co/edit/t8WcjuajSptQpdY72Rdb?p=preview

if you change the form, which inturn update the model, but doesnt hide the fields ..

**Comment by kentcdodds** [comment]
Oh, I get what's going on. One gotcha with formly (that should probably be documented) is that you can't re-use the exactly same fields between multiple forms. Another thing that you should avoid doing is using the same form for for multiple models. This is because when angular watchers are run, the model for the field may not be the model that you're expecting. So instead, for this case, where you have the same fields representing multiple models, I recommend each form having it's own copy of the fields and each `formly-form` having one model that doesn't get entirely swapped out (individual properties can be swapped of course, just not the entire object).

Here's an updated (working) plunker: http://plnkr.co/edit/z9SHYESTDGNHCN1bn0AX?p=preview

**Comment by kentcdodds** [comment]
If this resolves your issue, please close it :-)

**Comment by skchi** [comment]
Thanks.

I am trying to implement the solution you have provided in our use case, but i didn't understand why you are copying formfields upfront. I wouldn't know the formfields as its dynamically generated. Can you provide inputs around that.

**Comment by kentcdodds** [comment]
Sure, I copied the formFields upfront because I knew how many I needed, but you could easily copy them later, or create a function that returns a fresh copy of the fields. Like so:

```js
functon getFields() {
  return [
    // your fields
  ];
}
```

this would also ensure that each instance of the fields is unique. Then just invoke that every time you need a new copy.

**Comment by skchi** [comment]
i was already doing that.. but there is a typo which was causing issue .. now working fine ...

I am just concerned on the performance by storing the formdata and formfields .. for every operation... wouldn't it nice if we could just destroy the earlier data and update with the new data .. 

i really appreciate your help and inputs ...

**Comment by kentcdodds** [comment]
Well, that all depends on how many forms you've got... Let's move this to [gitter](https://gitter.im/formly-js/angular-formly) so we can chat more quickly.

**Comment by skchi** [comment]
I really appreciate your help .. thanks again ..

**Comment by kentcdodds** [comment]
(ó ì_í)=óò=(ì_í ò) Good luck!

**Comment by kentcdodds** [comment]
... Github... Messed up my emoji... `(ó ì_í)=óò=(ì_í ò)`
