### ISSUE TITLE
nghide removing the field from formData

### ISSUE THREAD

**Issue by vigneshkindia** [formly-js/angular-formly#170]
Hi,
I have been using formly for a while and came across this situation:
     When a field is hidden using the "expressionProperties", the value associated with the hidden field still remains in the formData. Is there any way to remove this field from the formData object?

Thanks.

**Comment by kentcdodds** [comment]
That's not a common use case, but one way to accomplish this would be via the `watcher`. You might do something like this:

```javascript
watcher: {
  expression: 'options.hide',
  listener: function(field, newVal, oldVal, scope) {
    scope.fields.splice(scope.fields.indexOf(field), 1); // removes the field itself
    delete scope.model[field.key]; // removes the field from the model
  }
}
```

I don't totally understand your use case, but doing this seems very odd to me and I would suggest finding another way to accomplish what you're trying to do.

**Comment by vigneshkindia** [comment]
Hi, 
Your reply helped. Thanks. 

The use case I am referring is explained here: http://jsbin.com/pevegavoli/2/

When i choose from yes to no, the reason given for yes, is retained in the form, whereas the field is actually hidden when u choose no. it doesn't make sense to have the hidden field data right?

correct me if I am wrong. I am still learning. :)

**Comment by kentcdodds** [comment]
Ah, I see, so you don't actually want to delete the property, you just want to change the value of the model. Well, the best way to accomplish this is likely still with a `watcher` but don't actually remove the field or use `delete`. Just set the value to null or an empty string. This is an edge case because the form's purpose is to represent the current state of the model, not alter it specifically. But if you wish to do this, I'd use `watcher`. Let me know if you have additional questions :-)

**Comment by kentcdodds** [comment]
Oh, and please close this issue if you have it working and you're happy with the solution.

**Comment by vigneshkindia** [comment]
its working fine.. :)
 thanks for the solution.
