### ISSUE TITLE
Support async validation for pre 1.3

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#172]
So the angular 1.2 crowd gets some love.

**Comment by egucciar** [comment]
Hi Kent, I found an issue with this. Unfortunately I must use 1.2.x, and found an issue with the validateModelOnChange property relying on $validate even though it is not available in 1.2.x. I have it fixed on my local and will aim to submit a pull request for your review, but don't need it merged back in immediately since we are currently working on a fork of this. Basically, I poly-fill the $validate function and make a call to $parsers instead. Here is the code snippet:

`
                function setupWithParsers(validator, name, isAsync) {
                    var inFlightValidator = void 0;
                    ctrl.$parsers.unshift(function evalValidityOfParser(viewValue) {
                        var isValid = nxnpjsonUtils.formlyEval(scope, validator, ctrl.$modelValue, viewValue);
                        if (isAsync) {
                            ctrl.$pending = ctrl.$pending || {};
                            ctrl.$pending[name] = true;
                            inFlightValidator = isValid;
                            isValid.then(function () {
                                if (inFlightValidator === isValid) {
                                    ctrl.$setValidity(name, true);
                                }
                            }).catch(function () {
                                if (inFlightValidator === isValid) {
                                    ctrl.$setValidity(name, false);
                                }
                            }).finally(function () {
                                var $pending = ctrl.$pending || {};
                                if (Object.keys($pending).length === 1) {
                                    delete ctrl.$pending;
                                } else {
                                    delete ctrl.$pending[name];
                                }
                            });
                        } else {
                            ctrl.$setValidity(name, isValid);
                        }
                        return viewValue;
                    });

                    if(!ctrl.$validate) {
                        // EG: I polyfill the $validate function so thate validateOnModelChange works
                        // why do we need to use 1.2.x :(
                        ctrl.$validate = function () {
                            angular.forEach(ctrl.$parsers, function (parser) {
                                var getType = {},
                                    isFunction = parser && getType.toString.call(parser) === '[object Function]';
                                if (isFunction) {
                                    parser();
                                }
                            })
                        }
                    }
                }
`

This works for one validator. I will need to implement a reduce for it to work with multiple and do some extra logic, most likely. I also need to check if the return needs to be adjusted (since right now I'm relying on the parser function internally setting the valid state and not caring about what I am returning from this function.) However my npm install isnt working and my POC with the later version of angular is broken until I can get that back and working. Will update you.

Thanks for having done some ground work on this!
