### ISSUE TITLE
Form data field is undefined when validation fails

### ISSUE THREAD

**Issue by dmatesic** [formly-js/angular-formly#196]
Example jsbin: http://jsbin.com/hujehojuli/1/

I modified the intro example to validate an input field as an e-mail field. When the field is valid (e.g. a@a), the form data json shows the field. But when the field is invalid (e.g. a@), the form data json does not show the field, because its value is undefined.

Is this intended behavior? This is an issue for me, because I am showing the data entered in the input field somewhere else on the page, but once it becomes invalid, the data disappears.

**Comment by kentcdodds** [comment]
This is how angular treats models that are invalid. If you want to override this behavior then you can use `modelOptions` (only if you're using angular 1.3 or greater). Otherwise you'll have to use the `$viewValue`. Here's an example of using `modelOptions`: http://jsbin.com/zuqojo Let me know if this solves your issue.

**Comment by dmatesic** [comment]
Wonderful, thank you!
