### ISSUE TITLE
Watcher on field with advanced layout

### ISSUE THREAD

**Issue by bfrijmersum** [formly-js/angular-formly#209]
Is there a way to use a watcher on a field when using the advanced layout functionality?

I adjusted the advanced layout example with only one field and added a watch which should write to the console, but it is not working: http://jsbin.com/tamixiv/1/edit?js,output

I might be doing something wrong and this might not be an issue.

**Comment by kentcdodds** [comment]
Yes, unfortunately this will currently not work. The `watcher` property is unique in that it is utilized in the `formly-form` directive, not the `formly-field` directive. The reason for this is that it allows your watcher to be active even if the field is hidden. However, because the `multiField` is iterating over the nested fields without using the `formly-form` (which it must to accomplish the advanced layout) so it is not able to take advantage of that property (sad day).

However, I rarely use the `watcher` property in my own stuff at work because there's normally an easier/better way to accomplish what I'm trying to accomplish. For example, in your `templateOptions` you can specify an `onChange` which will add an `ng-change` to your `ng-model` element. This may work just as well for what you're going for.

If that doesn't work for you, you can always specify a `controller` or a `link` for the field and do the watch there. Again, this wont be operative when the field is hidden... So you could get creative and make a field that has a template of `template: ''` and *that* has a `controller` or `link`. But that's a little crazy and I would be surprised if you needed to resort to this...

Finally, there's always just adding the `$scope.$watch` in your own controller. Not awesome from a reusability standpoint, but that's an option.

Let me know if you need any help with your specific use case.

**Comment by bfrijmersum** [comment]
Thank you so much for your explanation. I was not aware of the `onChange` and this is exactly what I need :)

**Comment by kentcdodds** [comment]
You're welcome!
