### ISSUE TITLE
Append dynamics fields

### ISSUE THREAD

**Issue by k010** [formly-js/angular-formly#243]
Kent, first to all the new version of angular-formly is awesome, thanks man !! 
i've a question, am trying to add some extra dynamics fields to the form but i can't do it successfully, i got some validation warning, this is my example [jsbin](http://jsbin.com/birizugora/1/edit?html,js,console,output)

What am doing wrong ?
Can you help me ?
Thanks !

**Comment by kentcdodds** [comment]
The problem is that angular-formly does a lot of things to your fields at compile time. If you reassign the fields after the form has been compiled, then that will cause a problem for you (as you can see).

So, instead of changing the fields, create another `formly-form` that will receive those new fields when they arrive. Put this behind an `ng-if="theNewFields.length"` so it only gets compiled when those fields are assigned.

**Comment by k010** [comment]
Thanks, for the reply !! 
am going to try it
:+1:

**Comment by kentcdodds** [comment]
Thanks! Let me know if there's anything I can do to make things easier for you!
