### ISSUE TITLE
Dynamic Fields (ie from API)

### ISSUE THREAD

**Issue by n0rb** [formly-js/angular-formly#246]
Hi Kent,

first I want to thank you and all the contributors for your awesome module!
I've been using it alot in my projects but I have one problem I cannot get around:

I mostly use a server API to provide the form metadata (form field definitions).
There are several requests to the API, ie onchangesubmit of a select value etc.
The API may or may not add/remove fields from the metadata on requests.

However if I don't clear the fields before setting the new fields, either the model gets screwed up (type mismatch ie between string and number) or formly throws an exception at some point.

The problem with clearing the fields and then setting the new fields (this actually only works using $timeout for setting the new fields), the page may flicker (just for a moment but you do notice it), lose focus etc because for a moment the document does not have the controls anymore and is blank.

Anyway I cloned an example from the formly examples and added a simple test to provide an example of the problem: http://jsbin.com/quyipiqenu/3/edit
it sets new formly fields after 5 seconds via $timeout.
the new fields contain one more input field, but as you can see formly "crashes" and renders two selects.

if you activate the prior $timeout, which clears the existing formfields at 4 seconds, the form will render correctly and produce no errors.

So, is there a way to dynamically update the existing fields of a formly form after it has been rendered ?
I hope you can shed some light on this issue which has troubled me since formly 1 ;)

**Comment by kentcdodds** [comment]
Thanks for using formly! You're not alone with this issue. Normally I've just explained that formly does some stuff at compile time and you can't just switch out the fields, but now I'm starting to think that this is a pretty common use case and people need this to work more seamlessly. So, I'm going to see how we can make this work with angular-formly without workarounds. I'll keep you informed.

**Comment by n0rb** [comment]
Thanks a lot for your fast response!
Yes, that functionality would be really great to have :+1:

**Comment by kentcdodds** [comment]
Started work on this. Not sure how I'm going to accomplish it. It's in [this branch](https://github.com/formly-js/angular-formly/tree/feature/246-dynamic-fields). Feel free to take a look if you want :-)

**Comment by joezhouOxford** [comment]
Hi Kent,
I encountered the same problem while developing my dynamic form builder. Basically, I want to dynamically switch out/change form field to "preview" the draft form on the fly. I got this error "Cannot read property 'show' of undefined
    at Object.watchShowValidationChange" . 
Do you have an workaround such as turn off the validation (which isn't ideal, if preview form can do the validation, it would give an more "realistic" preview)? 

Thanks

Joe

**Comment by kentcdodds** [comment]
Unfortunately a workaround like that wouldn't work. The validation issue is a side-effect of the real issue which is that the new fields aren't initialized properly.

**Comment by joezhouOxford** [comment]
Hi Kent
Thanks for the swift response!
I guess manually initialize the new fields are also not possible? 
If that is true then I guess the only workaround would be adding those new fields then refresh the page...

**Comment by kentcdodds** [comment]
Another workaround would be something [like this](https://github.com/formly-js/angular-formly/issues/230#issuecomment-90579649). I have a branch (as mentioned above) that I'm working on to make this possible by reinitializing the fields manually. This may be possible. But it will be a little difficult. Still more work to be done there.

**Comment by joezhouOxford** [comment]
Fantastic! Works like an charm :-) 
Many thanks

**Comment by kentcdodds** [comment]
whoops, this issue is still open and I'm still working on it...

**Comment by s992** [comment]
I'm also running into this issue when attempting to unshift or splice fields into my form. Your kcd-recompile workaround from #230 does work, but it introduces a noticeable lag when adding or removing fields.

I noticed that pushing new fields onto the array appears to work properly, but adding a field anywhere other than the end of the array causes Formly to throw errors. My fields have a unique ID stored in the data object, so I updated the formly-form directive to repeat formly-field with the expression `field in fields track by field.data.id` instead of `field in fields track by $index`. In my limited testing, this seems to work fine.

One issue with this approach is that fields without a key specified will not work properly. Because the model value is set based on the $index, it will assign the same model to multiple fields.

Would it be possible to add a "track by" configuration option to formly-form, but require that a key is specified for each field if a custom "track by" is used?

**Comment by kentcdodds** [comment]
@s992, that sounds like a reasonable solution for most use cases. I'll get this in as soon as I am able (probably by tomorrow). Thanks for your patience!

**Comment by s992** [comment]
@kentcdodds Great! Much appreciated.

**Comment by kentcdodds** [comment]
Note: master has the unreleased 6.1.1. Please see the [Changelog](https://github.com/formly-js/angular-formly/blob/master/CHANGELOG.md#611). The track by behavior changed (defaults to nothing), and you can also now specify your own track by:

```html
<formly-form model="model" fields="fields" track-by="$index"></formly-field>
```

or 

```html
<formly-form model="model" fields="fields" track-by="field.key"></formly-field>
```

or

```html
<formly-form model="model" fields="fields" track-by="vm.trackWhateverIWant(field)"></formly-field>
```

I'm now waiting on @s992 and @n0rb to tell me how this supports your use case before I do an official release. Thanks!

**Comment by s992** [comment]
@kentcdodds Tested your changes briefly this morning and it looks like it works for my use case. I'll be working with Formly for most of the day, so I'll update you once I've spent a little more time trying to break it. :)

**Comment by kentcdodds** [comment]
If you do break it, feel free to [add a failing test](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.test.js#L212) and I'll take it as a challenge :-)

**Comment by n0rb** [comment]
@kentcdodds Thanks for the update! and @s992 thanks for your input on this issue!
I probably won't get to test this thoroughly before next week but a few quick tests look promising :+1:

**Comment by kentcdodds** [comment]
So, I just realized that by adding this new functionality, it actually allows you to totally swap out fields! I had no idea that the `track by $index` was the culprit here! Please still let me know when you've tested it out, but I'm pretty confident that between [this test](https://github.com/formly-js/angular-formly/blob/e2178dccf6f97d2d51febba8cbf453e090d482d4/src/directives/formly-form.test.js#L108) and [these tests](https://github.com/formly-js/angular-formly/blob/e2178dccf6f97d2d51febba8cbf453e090d482d4/src/directives/formly-form.test.js#L221-L274) we should be covered :-D

**Comment by s992** [comment]
@kentcdodds Seems to be working great for my use case. If any problems do crop up, I'll be sure to let you know.

Thanks for such a quick response!
