### ISSUE TITLE
Support multiple ng-models

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#275]
I think it'd be good to make it set the `formControl` to an array if there are multiple `ng-model`s

**Comment by kentcdodds** [comment]
@ckniffen and @Den-dp were having a talk on [the Gitter chat](http://gitter.im/formly-js/angular-formly) today about this same issue. @ckniffen created [an example](http://jsfiddle.net/W99rX/) of a directive that could do this. Thanks!

**Comment by kentcdodds** [comment]
Not sure whether this will require a breaking api change or not. I don't think so, but it looked too difficult to accomplish in the 6.4.0 release so I've pushed it back to 6.5.0

**Comment by ckniffen** [comment]
Does it need to make the assumption that all elements with ngModel map to the same value.

I ask because of https://github.com/formly-js/angular-formly/blob/573a9b070097f1ccd8f55eada4df2f8be7255e4e/src/directives/formly-field.js#L155.

**Comment by kentcdodds** [comment]
Yeah, you know what. I think this issue doesn't really make sense...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ckniffen** [comment]
I think it is still valid use case.  I have run into myself with a date-picker and time-picker directive in one field template.  I will have a PR sometime tonight.  It will only work if each instance of `ngModel` has a different name though.

This will not fix the symptoms seen in https://github.com/formly-js/angular-formly-templates-bootstrap/issues/19 though because in that case each element with `ngModel` in that template has the same name.  The following use case is the one that will be covered:

```html
<input type="input" name="start" ng-model="options.model[options.key].stop" />
<input type="input" name="stop" ng-model="options.model[options.key].start" />
```

The tests I will be adding cover resetModel and that the formControl is made an array in case of multiple ng-model elements.  Are there any other features that leverage formControl?

**Comment by kentcdodds** [comment]
I can't think of other features that use the `formControl` directly. I wonder if there's something we can do in the `ngModelTemplateManipulator` (which is responsible for setting the name) to handle multiple `ng-model` elements by setting a unique name for each.

**Comment by kentcdodds** [comment]
Thinking about it more, I think that we definitely should have that feature in the `ngModelTemplateManipulator`. Do you think you could add that to this PR? You'll know it's working when your tests pass when you omit the `name` on your `ng-model`s. Should probably add a test in `ngModelTemplateManipulator` as well.

**Comment by kentcdodds** [comment]
Also, thanks for taking this one. It's far from a simple feature.

**Comment by kentcdodds** [comment]
Supported in `6.12.0-beta.0`. Anyone watching, please test your stuff to make sure we didn't break anything!

**Comment by kentcdodds** [comment]
Note, all of the examples on the website seem to be working fine :+1:

**Comment by SabariRaja27** [comment]
hi all..is this issue got fixed?...I'm also facing the same issue for check boxes.whether i should create a new customised directory.Did any one tried the directory??
