### ISSUE TITLE
Specifying root-el prevents vm.form from being populated

### ISSUE THREAD

**Issue by s992** [formly-js/angular-formly#279]
JSBin example: http://jsbin.com/molulomugi/1/edit?html,output

I tried to write a failing test for it, but I can't get the tests running on my system.. looks like an issue with the Babel loader. The failing test would probably look like this:

```js
it(`should place the form control on the scope property defined by the form attribute when root-el is specified`, () => {
  compileAndDigest(`
    <formly-form root-el="div" form="vm.myForm" model="model" fields="fields"></formly-form>
  `);
  expect(scope.vm).to.have.property('myForm');
  expect(scope.vm.myForm).to.have.property('$name');
});
```

**Comment by kentcdodds** [comment]
If you use anything other than <form> or <ng-form> then there's no form
controller to provide you with. So that simply wouldn't even make sense in
that case.

The solution is to wrap the <formly-form> in an ng-form or form which has a
name attribute, and pass that same value to the formly-form form attribute.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by s992** [comment]
D'oh! Makes sense. Thanks :)
