### ISSUE TITLE
Drop angular 1.2 support? Please comment.

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#324]
Please comment on here if you're using angular 1.2. I don't plan on dropping support anytime soon, but I'm curious to know how many people are currently using angular-formly with angular 1.2. If you are on angular 1.2, let me know if there's any reason that you can't upgrade to 1.3 (or wouldn't be able to in the future).

**Comment by mikeerickson** [comment]
>=1.3 is good for me, dont have any 1.2 projects

**Comment by koenweyn** [comment]
We're still using 1.2 because we need to support IE8. I wish we didn't, but alas ...

**Comment by s992** [comment]
We're currently using 1.2 for IE8 support. We plan on dropping IE8 at some point (it's being discussed), but I have no idea as far as the timeline goes.  That being said, I am 100% for dropping 1.2 support if it means you can make Formly better - all I ask is that you provide a clear version number cutoff for when support is officially dropped so that we can lock down our dependency to that version.

**Comment by kentcdodds** [comment]
Don't worry, it's actually not *too* painful to support Angular 1.2 right now, but I'm curious to hear how many people are using angular-formly with angular 1.2. I will likely eventually drop support, but when I do, it will definitely be a major version change, so you shouldn't be auto-upgraded. And I'll make an announcement (so [follow me on twitter](https://twitter.com/kentcdodds))

**Comment by kentcdodds** [comment]
Closing. I don't think I'll be dropping 1.2 support for a while, it's really not a huge pain to support right now (though I do have some custom code for it that would be nice to get rid of). I'll comment in this issue if I'm thinking about dropping support, and don't worry, as long as you use a `^` or `~` in your dependency listing, I wont push a break to you (because it'll be part of a major version change).

**Comment by PascalPrecht** [comment]
Hey everyone,

I haven't used angular-formly myself yet. Recently it popped up, that angular-formly doesn't support `controllerAs`, as it tries to keep support for Angular 1.2.x. I have a couple of thoughts on this:

- **controllerAs is part of Angular 1.2.15** maybe even earlier, as we can see here: https://code.angularjs.org/1.2.15/docs/api/ng/directive/ngController. If this is a reason to not drop support for Angular 1.2.x, I think this can be done now. As long as devs upgrade in 1.2.x range, there should be no problems.

- **Parsers/Formatters/Validators** - Validators have been introduced in Angular 1.3. Before that, we used parsers and formatters to validate input values. Since parsers and formatters still exist in Angular 1.3, because they still doing their job of parsing and formatting, I don't see any reason to drop support for 1.2 that feature. AFAIK this extension opts in anyways, and falls back to parsers and formatters in case no validators are supported. So that's fine.

Maybe support for Angular 1.2 doesn't have to be fully dropped, but angular-formly should move on and use `controllerAs`, since this is one of the very first best practices that Angular devs learn today. They should avoid using `$scope`. Not sure what else keeps you from upgrading, but if it's `controllerAs` I'd recommend making it a requirement that the version of Angular that is used supports it.

**Comment by kentcdodds** [comment]
Thanks for the input @PascalPrecht!

For everyone, updating angular-formly to drop support for 1.2 costs me more time than leaving support for 1.2 right now, so I think that I'll leave it as is because it's working well and doesn't hinder the experience of developers using the latest version of angular. *But support for 1.2 will be dropped eventually for sure.* But again, it will be in a major release version so as long as you're using exact versioning or you're using `^` or `~` you should be fine.

**Comment by jmls** [comment]
I personally think that saying v6/v7 will be the last release that supports 1.2 is just fine. At least that way v7/v8 can be coded with the new stuff in 1.3 (1.4?) in mind rather than be constrained by having to support an older version of angular

ie, if you want the new stuff in formly, move to 1.3.

**Comment by kentcdodds** [comment]
Yeah, I think that v7 will likely be the last version to support IE. I'll remove support for it in v8 (👈 not the JS engine...) :-)
