### ISSUE TITLE
Siren action support

### ISSUE THREAD

**Issue by XVincentX** [formly-js/angular-formly#338]
I think it would be really great if angular-formly could accept as input a [siren action](https://github.com/kevinswiber/siren)

**Comment by kentcdodds** [comment]
Looks "super rad" :wink: However, it's definitely out of scope for angular-formly. But, I would be happy to create a repo called angular-formly-siren-action and give you permissions to develop a plugin for angular-formly that would convert a siren action into a field configuration that angular-formly can understand. And if angular-formly needed to make a change or two to support that kind of plugin architecture, then I would be happy to make that as well. We're doing the same thing with [json-schema](https://github.com/formly-js/angular-formly-json-schema) (though, nobody's really taken ownership of that yet).

Either way, I'm going to close this issue now because it's out of scope.

**Comment by XVincentX** [comment]
Hey,
generally speaking, all the hypermedia world is very cool, even if still coarse. For example, Siren is actually the only hypermedia format that supports the "action" concept. Other ones, like CJ or HAL, stops at `link` support.

Given that, I may be interested in contribution for that, but I have no ETA. I am working on a small project and I definitely will try to use your component. After that, I will try (if I'll have some time left) to extract my work and contribute back to your project.

**Comment by kentcdodds** [comment]
Sounds perfect. When I get back to the computer, I'll set up a blank repo
and add you as the contributor so anyone else who's interested can ask you
about contributing :-) Thanks for your interest!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Created: https://github.com/formly-js/angular-formly-siren-action/issues/1
