### ISSUE TITLE
id="" and name="" are treated like the same thing?

### ISSUE THREAD

**Issue by cfv1984** [formly-js/angular-formly#341]
Hi! 
  I've been trying to make this happen: 
    `<input type="text" id="some_id" name="totally_different_field_name" />` but haven't been able to, using either angular-formly-templates-vanilla, angular-formly-templates-bootstrap. Only by making my own type
```
    {
      name: 'silly-input',
      extends: 'input',
      template: '<input type="text" ng-model="model[options.key]" name="{{to.name}}">'
    }
```
I've been able to incorporate said change, and it does sound pretty silly to incorporate such a (from my perspective) common use case. The id attribute and name attribute are separate and disjoint attributes used for different things since pretty much the dawn of javascript, id being a ref for javascript and inline anchors and name being the actual "name" part of a form's held key-value pairs.

Am I missing something from the docs? Is there a more idiomatic manner of doing this? Will I have to wind up making templates for every single form input type to change this?

**Comment by kentcdodds** [comment]
Most modern angular applications don't need the `name` to be anything special, just unique. If you have this use case, you have a bunch of different ways you could accomplish it. My recommendation: create your own types, don't use one of the template libraries. I would say that your use case is not common for modern applications. Luckily, angular-formly is pretty darn flexible and creating custom templates is quite easy.

You could do this using `ngModelAttrs`, however it's a bit of a complicated API and I would actually just advise creating your own template to accomplish what you want in this case. It is intended that the `id` and the `name` are something that you don't need to think about and hence, the template libraries don't come with this capability out of the box.

...

Thinking about it further... I think that it wouldn't be unreasonable to bring this functionality into angular-formly. Currently, you can specify your own `id` as part of the field configuration object. This will be propagated to both the field's `id` as well as its `name`. I don't think it's unreasonable to allow you to specify a `name` property as well which would be used for the field's `name` if present, otherwise it would default to the `id`... What do you think?

**Comment by cfv1984** [comment]
Hi Kent! Thank you **VERY** much for the prompt response. 

I've indeed begun building my own template library, and indeed my names and ids are different in there through the templateOptions hash. 
In this particular use case, there is a preexisting backend that consumes the form, to which we don't really have frequent access, and it needs its values in the form `name="form[nested][0123][key]"`. This wouldn't necessarily be a problem, but as there is a preexisting frontend too, which in assorted places will look for ids in the form `id="form_nested_0123_key"` that'd mean having to track down and update any and all references to the thing wherever they might occur. 

I understand it's indeed the case that for *new* applications or even preexisting SPAs that the name of an input is not really relevant, but for preexisting apps or even some styles of markup generation it can be a pretty big deal. 

The *meaning* of an ID vs a name are different, and I'd indeed be very grateful if such a thing could be represented more naturally in formly. 

Again, thank you very much!

**Comment by kentcdodds** [comment]
You've convinced me. I'll try to get to this asap.

For anyone looking to contribute, here's a high-level of what needs to be done:

1. Write a few tests (probably [here](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.test.js#L39)):
  - `name` (on both the `options` object and on the scope) defaults to random thing that's the same as the `id`
  - `name` is the same as `id` when an `id` is specified
  - `name` is equal to the `name` property specified on the field options object (and is different than the `id`)
2. Add `name` to the api-check for a field. Somewhere around [here](https://github.com/formly-js/angular-formly/blob/master/src/providers/formlyApiCheck.js#L92)
3. Add `setFieldName` logic to the `FormlyFieldController`. Somewhere around [here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L49) potentially even change `setFieldId` to `setFieldIdAndName`... Do something like `$scope.options.name = $scope.options.name || $scope.options.id` at the end
4. Update [this](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.js#L27) line to use `scope.name` rather than `scope.id`.

I'd recommend giving [this](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) a watch if you haven't already.

If nobody gets to this before I do, then that's fine...

**Comment by kentcdodds** [comment]
Thanks to @benoror, this is now supported in 6.13.0. Thanks!

**Comment by benoror** [comment]
:smile:
