### ISSUE TITLE
data-* atributes support and attribute-style directive

### ISSUE THREAD

**Issue by redhead** [formly-js/angular-formly#357]
I want to report a bug as I presume. Since Angular can deal with attributes with `data-` prefix by stripping it, I thought it would work as well in Formly. But when I used `fieldGroup`, an error which didn't make any sense appeared and the form didn't work:

    <formly-form data-model="vm.model" data-fields="vm.fields" data-form="vm.form">...

When there is a `fieldGroup` in the field configuration, this weird error is raised

    Syntax Error: Token 'vm' is an unexpected token at column 20 of the expression [options.fieldGroup vm.fields] starting at [vm.fields].

and in HTML I see

    <ng-form ... data-model="model vm.model" data-fields="options.fieldGroup vm.fields" data-form="options.form vm.form">

I think this is a bug, since Angular handles attributes with data- prefix well.

Also, is there any reason why `formly-form` directive is only restricted to element? I think attribute would work as well. Rationale is, in our project we use a convention that directives are specified in attribute form (with data- prefix) and all directives' attributes as well. So if it worked as this also, it would be great:

    <div data-formly-form data-model="..." data-field="..">...

**Comment by kentcdodds** [comment]
This is indeed a bug. `fieldGroup` uses a `formly-form` itself and it copies attributes and their values from the parent formly-form (except for attributes like `model`, and `fields`). The problem is that it should also account for `data-model` and `data-fields` etc. You're welcome to make a PR. Otherwise I'll look at this as soon as I am able...

Should be pretty simple, just need to add the data counterpart to [this array](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L91)

**Comment by redhead** [comment]
It's not necessarily a blocker for us, if I get a bit of time I will look at it tomorrow (if as you say it's just as easy as extending the array). Thanks.

As for the attribute style directive restriction, is it possible or do you think it'll breaks something?

**Comment by kentcdodds** [comment]
I don't think that there would be a problem with adding the attribute style to this directive. It's technically more of a "component directive" so it makes more sense as an element, but I'd be find to open it up as an attribute.

**Comment by kentcdodds** [comment]
Thanks for the PR @redhead! This is available in `6.15.2`
