### ISSUE TITLE
Add parsers and formatters

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#368]
Feedback appreciated: It would be really handy to be able to specify parsers and formatters (to support use cases like [this](http://stackoverflow.com/q/31066409/971592). Something like this:

```javascript
vm.fields = [
  {
    type: 'input',
    parsers: [appendCurly],
    formatters: [hissToSnake]
  }
];

function appendCurly(value) {
  return value + '}';
}

function hissToSnake(value) {
  return value === 'hiss' ? 'snake!' : value;
}
```

Some cases to consider:

1. When merging the fields with `defaultOptions` we need to decide what order to apply the parsers and formatters (considering the order they are run in...)
2. Should we provide a mechanism to override `parsers` or `formatters`? We could allow you to specify a property on the function that identified the parser/validator (like `id`) and that would be used to override them.
3. Anything else I'm missing?

**Comment by ckniffen** [comment]
Is this for shiming the features of angular-1.3 with formly?

**Comment by kentcdodds** [comment]
@ckniffen, not sure I understand what you mean. The `$parsers` and `$formatters` apis are available in angular 1.2

**Comment by ckniffen** [comment]
Sorry I was thinking of $validators.  That aside would this leverage $parsers and $formatters?

**Comment by kentcdodds** [comment]
Yes, it would be similar to [`formly-custom-validation`](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-custom-validation.js) except it would do something like: `ctrl.$parsers = ctrl.$parsers.concat(options.parsers)` or `ctrl.$parsers = options.parsers.concat(ctrl.$parsers)` depending on which order we decide to apply the new parsers.

Then there's the decision on how to merge them...

**Comment by benoror** [comment]
Shouldn't it just rely on NgModelController's `$parsers` & `$formatters` existing functionality?

https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$parsers

**Comment by kentcdodds** [comment]
@benoror, yes, it will, that's what I'm planning on doing. But we need to consider `defaultOptions` and overriding as well as considering existing $parsers and $formatters.

**Comment by kentcdodds** [comment]
That's mostly what I want feedback on (noted in the numbered list above)

**Comment by benoror** [comment]
My toughts:

1. Since "*The functions are called in reverse array order*" I think the ones in `defaultOptions` should have more precedence, therefore should be **pushed _last_**
2. Since pushing a function with the same name won't override it, I see 2 possible opts:
    1. A simple mechanism to override `defaultOptions` when specifying the same name
    2. Use of ID's to specify overriding

**Comment by kentcdodds** [comment]
Sounds good.

For your "as an object" suggestion, I considered that as well. The problem is then you have to figure out how to determine which to push on the pipeline first. So I think that an `id` would probably be better. But can anyone think of a use case where this would be needed? I think I'll leave it out until someone mentions they need it...

**Comment by zeddever** [comment]
+1 for this, I was about to open a PR for comments when I saw this one.

WRT a use case, I currently have dates that I push from the server in ISO8601 but allow the users to edit it in a more user friendly format. Ergo I'd need the parser/formatter framework to keep my model consistent. Of course I could go implement a directive but it felt like a better fit for this framework. Model transformation is a pretty common operation hence the support for a MV transformation framework being built as a part of angular core. Formly is essentially presenting a new interface (the old one being declarative HTML through the use of directives) to the form control features that angular supports but Formly doesn't give any interface to the formatters/parsers abstraction, which makes it an incomplete interface.

 FYI, atm I have an extra 'Editor' abstraction between my actual model and my formly model and this abstraction allows me to do transformations outside of the parser/formatter framework.

Please implement this, as I think it would bring your framework full circle wrt interfacing to angular form functionality.

WRT the points you raised:
1) I also think defaults should take higher precedence, i.e. they should go to the end
2) I don't think you need to be able override parsers/formatters. It's a chain, and with defaults taking precedence, you can "override" by adding a formatter/parser later in the chain that transforms what the default formatter gives you. If using a particular form custom type, there are certain characteristics that you should expect of that the contract provided by that form type, and it's these abstractions that you should be working with in you code. 
E.G. if your working with a "date input" type it might include default parsers and formatters to keep the model consistently a date object and the view consistently a string formatted as a 'fullDatetime'. If you wanted to customize that field type, eg, to change the format of the text in the input field, then you look at the interface documentation for the field and you know the new primitives to work with. I.E. to change the format, you need to either do the string munging manually, or better yet parse the new formatter primitive which is a 'fullDatetime' formatted string, then reformat the parsed string to your hearts content. ON the other side, if you wanted to change the parsers chain, eg, maybe to add an offset to the date, the new primitive would be the date object that the contract that the "date input" field guarantees. If you need something outside of what the contract for the field guarantees, then you should make a new type all together or create a new abstraction where it makes sense. The field type should be immutable wrt it's contracts for the data interfaces.

Another potentially hairier issue is that if you try to override a part of an existing default chain segment then parts of that default chain segment might break since you might change the interface that a sub segment of that default chain segment expects.

Thanks for the great work on this library so far, and I hope you'll roll out this feature

**Comment by kentcdodds** [comment]
Here's my plan for implementation:

When merging parsers, they will be concatenated together. Options can be merged in four scenarios. This is the order the parsers will be concatenated (meaning the parsers will run from the top of this list to the bottom):

1. Extended type
2. Type
3. `optionsTypes` (in order specified)
4. `parsers` specified on the field

For example:

```javascript
formlyConfig.setType({
  name: 'parent1',
  defaultOptions: {
    parsers: [parent1Parser1, parent1Parser2]
  }
});

formlyConfig.setType({
  name: 'parent2',
  defaultOptions: {
    parsers: [parent2Parser1, parent2Parser2]
  }
});

formlyConfig.setType({
  name: 'child',
  extends: 'parent1', // <-- note this!
  defaultOptions: {
    parsers: [childParser1, childParser2]
  }
});

formlyConfig.setType({
  name: 'optionType1',
  extends: 'parent2', // <-- note this!
  defaultOptions: {
    parsers: [optionType1Parser1, optionType1Parser2]
  }
});

formlyConfig.setType({
  name: 'optionType2',
  defaultOptions: {
    parsers: [optionType2Parser1, optionType2Parser2]
  }
});

// parser definitions excluded for brevity...

// elsewhere... in some controller
var vm = this;

vm.fields = [
  {
    type: 'child',
    optionsTypes: ['optionType1', 'optionType2'],
    parsers: [fieldParser1, fieldParser2]
  }
];
```

The resulting merged array for this field's parser would appear as:

```javascript
[
  parent1Parser1, parent1Parser2,
  childParser1, childParser2,
  parent2Parser1, parent2Parser2,
  optionType1Parser1, optionType1Parser2,
  optionType2Parser1, optionType2Parser2,
  fieldParser1, fieldParser2
]
```

Formatters will be the exact same.

Could someone sanity check me on this one? It's a little confusing, I don't use parsers/formatters very often, so someone with more experience may be able to help me to determine the most logical solution. I think this is correct though. Just want to make sure that I'm covering my bases!

P.S. Doing something like this with that many parsers would be utter insanity... Just had that thought :-) But this is a very contrived example

**Comment by benoror** [comment]
Although this is an edge (but maybe not too unrealistic) example, I agreet as this is what I would expect from an execution-order standpoint: the more specific a {parser,formatter} is, the later it will be applied.

**Comment by kentcdodds** [comment]
Note, in the case of formatters, they will be executed in reverse order as indicated by the docs. But I believe this is also desireable behavior...

**Comment by a-laughlin** [comment]
+1

**Comment by koenweyn** [comment]
I would love to be able to use this feature, or alternatively, if formly would provide the ngModelController to the link function, I could add parsers and formatters myself.

**Comment by kentcdodds** [comment]
Just got the above example to pass as a test for parsers. I'm going to push this up into master. I would really appreciate if interested parties try it out and ensure that it works as you expect. I'll be working on formatters next. After I get some feedback (and fix anything) then I'll release a beta so more people can try it out. I'm concerned about getting this feature right, so please help by trying it out.

**Comment by kentcdodds** [comment]
Sorry, jumped the gun. I broke several other tests with my implementation. I'll comment when I've actually pushed the parsers stuff.

**Comment by kentcdodds** [comment]
Alright, it's working great! I've decided to make all parsers evaluate as formlyExpressions which means they can be expressed as strings and they also have access to the field's scope (and therefore the field's `options`). Also, I've actually just released a beta version that has parsers support. Again, please test it out and make sure I haven't missed anything important. I'll add formatters once I hear that parsers is working out for people (should reuse much of the same code).

```
npm install angular-formly@6.21.0-beta.0
```

**Comment by kentcdodds** [comment]
Alrighty, `formatters` support is in the next beta version. Please provide feedback:

```
npm install angular-formly@6.21.0-beta.1
```

**Comment by kentcdodds** [comment]
Has anyone had a chance to validate that this works as you'd expect? I don't really have a use case for this in my app, so it's hard for me to know whether it makes sense as implemented.

**Comment by zeddever** [comment]
WRT my expressed interest, I've already shipped the app with the workaround
I mentioned and I've already moved on to a new app with a different stack
(i.e. not a web app) so I don't have a harness or the time to set up a new
one atm so I can't test it atm. Your notes on the implementation are inline
with what I was expecting though, so for my 2 cents, it's a go. I do have
another app coming up where I might need to use this feature so I'll
definitely be able to check it out then, and I'll submit a PR or two if I
find any issues.

Thanks for the quick implementation of the feature and I hope it'll come
out of beta in time for me to use it in a couple months

**Comment by kentcdodds** [comment]
It's out of beta :-) Thanks for the feedback!

**Comment by koenweyn** [comment]
Hi @kentcdodds, I finally had some time to play around with the new parsers and formatters.
Everything works as expected, except formatting of the initial model value. When you start up with an already initialised model value, formatting is not applied, because the formatters are only added at a later stage.
You can work around this by adding a link function that formats the value as soon as the FC is known to the scope. See the example [here](http://jsbin.com/tiwuha/edit?js,console,output).
Is there something that can be improved in formly so that the workaround is not needed?

**Comment by kentcdodds** [comment]
Thanks for trying it out @koenweyn! I'm sure that we could make it work without trouble. It would amount to adding that logic you have to [this function](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L361). This seems like a good opportunity for a [`first-timers-only`](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. Do you think that you could file a bug separately and I'll prepare the issue for a first timer? (you could even prepare it if you would like).

**Comment by koenweyn** [comment]
Preparing the issue would just mean writing a failing test and marking it as `it.skip`, correct?

**Comment by kentcdodds** [comment]
Precisely :-) You can see [the others](https://github.com/formly-js/angular-formly/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afirst-timers-only+)

**Comment by koenweyn** [comment]
On it!

**Comment by synthecypher** [comment]
Can we get some docs for this feature?

**Comment by kentcdodds** [comment]
@synthecypher, I created an example for the website. It will be live soon. If you can't wait 3 more minutes for it to deploy, [here it is](http://jsbin.com/luwoso/edit?html,js,console,output) :-)

**Comment by mhawila** [comment]
It would be nice if it was possible to use this feature to define default parsers and formatters when creating new types. I have been trying to set this on a new datepicker type without success. I get an error field can not be added with a list of fields I can define. Any comment @kentcdodds ? Thanks.

**Comment by kentcdodds** [comment]
You add them as part of the `defaultOptions` :-)

**Comment by mhawila** [comment]
@kentcdodds thanks I realized it didn't work because I was using version 6.x, upgrading to 7.x fixed the issue even though now the model is not updated. I mean the formatters and parsers are called but somehow the model is empty. I don't know if this has anything to do with event chain(?)

**Comment by kentcdodds** [comment]
The best way to get help is to follow the instructions here: http://help.angular-formly.com
