### ISSUE TITLE
Improve async validators

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#369]
Currently, all validators that are functions are pushed into angular's `$asyncValidators` api. Per [this comment](https://github.com/angular/angular.js/issues/10955#issuecomment-72780406) there can be issues with this.

I'm suggesting that you can optionally specify a function as synchronous if you want to avoid those issues. I think it'd work something like this:

```javascript
vm.fields = [
  {
    // ...
    validators: { isFoo }
  }
];

function isFoo($viewValue, $modelValue, scope) {
  return $viewValue === 'foo';
}
isFoo.isSync = true;
```

*side note*: For a short while, angular-formly supported the opposite of this with an `isAsync` property but that was just cumbersome and confusing so we opted to get rid of it and make all function validators use the async pipeline. This feature would be an optimization you could make if some of your validators actually make API calls. However, I would be willing to bring that back if people think it's a better solution/api (which it very well may be).

**Comment by a-laughlin** [comment]
What's the purpose of having a single validators object currently?  If it's to keep things simple, I think the simplicity is lost when needing to add new properties to disambiguate between them.  Using the existing angular syntax seems the simplest and easiest to understand, since there's nothing new to learn:
```js
vm.fields = [{
  validators:{},
  asyncValidators:{},
}]
```

**Comment by kentcdodds** [comment]
Thanks for commenting @a-laughlin. I actually like that idea a lot. Unless someone comes along with a good rebuttal, I think this is what I'll do.

This can be implemented as a "smooth" breaking change, as in, I'll add the `asyncValidators` property, and add a console warning to any non `asyncValidators` validator that returns a promise that this api is being deprecated and they must either return `true` or `false`, or they must use the new `asyncValidators` api.

Would love more input (even if it's a :+1:). I think this is where I'm going.

**Comment by a-laughlin** [comment]
:+1:

**Comment by ckniffen** [comment]
:+1:

**Comment by kentcdodds** [comment]
Released as `6.18.0`. Not a breaking change. Simply allows you to add `asyncValidators` explicitly. Also, you can specify `formlyConfig.extras.explicitAsync` which will prevent any of your `validators` from being placed onto the `$asyncValidators` pipeline.

**Comment by kentcdodds** [comment]
Just updated [the example](http://angular-formly.com/#/example/other/unique-value-async-validation)

**Comment by luckyagarwal3247** [comment]
Hi Kent,

I am using this async validator as shown in the example, except that I'm not using the loader animation so there is no timeout of 1sec. 

I noticed that the error thrown shows up in the browser console as soon as i finish typing an invalid value, but neither the field is set as invalid nor the validation message shows up below the field immediately. I understand its because of the blur model option. How can I modify it to update the field too immediately?

**Comment by CodeLiftSleep** [comment]
Is there a way to run multiple async validators on a field?  For instance, I need to make one call to see if an access code is registered more than 5 times, and another call to see if the person is already in the database, and these are two separate calls to two separate Controllers.
