### ISSUE TITLE
integration with translate

### ISSUE THREAD

**Issue by syzer** [formly-js/angular-formly#373]
here form does not update translations
if translation language is changed in navbar.

[jsbin](http://jsbin.com/higepoheco/edit?html,js,output)

**Comment by kentcdodds** [comment]
It's because `expressionProperties` only run when the `formState` or the `model` changes. Doing this saves big time on watchers (two watchers per form rather than two per field). You'll need to either bind the tabs model's to `formState` (probably easier) or you'll have to add a `$watch` to your controller and invoke the `runExpressions` function on the fields yourself. Like this: https://jsbin.com/hijoci/edit?html,js,output

**Comment by kentcdodds** [comment]
Thanks for including a jsbin that reproduces your question. Makes it much easier to help!

> &lt;canned-message&gt;
> 
> Thanks for your interest in angular-formly. The issues are for bug reports/feature requests, so I'm going to go ahead and close this issue. If you have a question or need help, please [watch this screencast](https://www.youtube.com/watch?v=NXqFiSeBE-M&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) for an explination of the most effective/proper way to get help using angular-formly.
> 
> Summarized:
> 
> 1. [Learn angular-formly basics](http://learn.angular-formly.com)
> 2. [Check the examples](http://angular-formly.com)
> 3. [Reproduce the issue](http://help.angular-formly.com)
> 4. [Ask on Stack Overflow](http://stackoverflow.com/questions/tagged/angular-formly)
> 5. [Ask on the mailing list](http://mailing-list.angular-formly.com)
> 6. [Ask on Chat](http://chat.angular-formly.com)
> 
> P.S. sorry for the canned message, this just happens a lot :smile: 
> 
> &lt;/canned message&gt;

**Comment by syzer** [comment]
:+1: thanks.

**Comment by casoetan** [comment]
thanks for this. Hope someone steps up to maintain this.

**Comment by diegochavez** [comment]
Updated jsbin https://jsbin.com/mamiyuz/1/edit?html,js,output

**Comment by U-like** [comment]
Why not to listen on the `$translateChangeSuccess` event fired by translate lib?

```
$rootScope.$on('$translateChangeSuccess',function(){
      angular.forEach(vm.fields, function(field) {
          field.runExpressions && field.runExpressions();
        });
    });
```

Like [this](https://jsbin.com/tuniqe/2/edit?html,js,output).

**Comment by ewcchan** [comment]
I tried to follow the steps above but the translation does not work in fields of type select or radio (as also shown in the jsbin in https://github.com/formly-js/angular-formly/issues/373#issuecomment-250988345), also failing to work with fieldGroup.

**Comment by ashthespy** [comment]
@ewcchan I think I am doing something silly here, but I can't get your example to work.
Do you have a JSbin of it by any chance? I am having trouble getting the filed types of radios and checkboxes to translate

**Comment by gmanriqueUy** [comment]
Hi @ashthespy. [Here](https://jsbin.com/pufigen/4/edit?html,js,output) you have a JSbin with a working example of @ewcchan's solution.

**Comment by ashthespy** [comment]
Thanks for that @gmanriqueUy! 
Just a query, is it possible to predefine the option fields, say like [this](https://jsbin.com/futuheguqo/edit?html,js,output)?
Just a matter of code preference, but I'd like to have all my field options defined in one place rather than sprinkled around the forms.  Or would that not be possible?

**Comment by gmanriqueUy** [comment]
@ashthespy, I think I'd do it like [this](https://jsbin.com/qehahuf/1/edit?html,js,output).
Notice the use of the angular constant and the translation made inside of the formlyExpression function.
