### ISSUE TITLE
Hide the asterisk into the label when a field is required

### ISSUE THREAD

**Issue by b-barry** [formly-js/angular-formly#379]
Hello,

Excellent library. It's very powerful. 
 I have a question about the asterisk: 
Are there a simple way to hide it  like disabling the label field ?

Thanks,

**Comment by anisylen** [comment]
Did you find a solution?

**Comment by b-barry** [comment]
No, I don't check It in the end.
Sorry, I would close it

**Comment by anisylen** [comment]
@b-barry I'm sorry I don't understand you...?

**Comment by b-barry** [comment]
For my project,  the requirement was to hide the asterisk at first. But after discussion, we decide to keep It that why I closes the issue.

Sorry, I should have been more explicit.

I think that you can check css class of the asterisk and hide It for exemple

**Comment by anisylen** [comment]
Ah ok sure. But I feel the issue can be opened because there hasn't been an actual solution to your problem. But reopening this issue would just be noisy so I'll create another issue about this.

**Comment by b-barry** [comment]
Ok. Feel free to create a new issue to get a solution

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!
