### ISSUE TITLE
Binding a Breeze.js object to the formly-form ng-model : Out of stack space

### ISSUE THREAD

**Issue by DeBiese** [formly-js/angular-formly#397]
I have been playing around a bit with formly the last couple of weeks.
Yesterday I tried bringing some pieces of my puzzle together and I ended up getting a console full of errors about the stack being out of space.

The pieces I brought together were:
- Breeze.js for data access (http://www.getbreezenow.com/breezejs)
- UI Tree for visualization (https://github.com/angular-ui-tree/angular-ui-tree)
- Formly for modifying data bound to the UI Tree

After some elimination, the issue seems to occur when I bind a breeze data object to the formly form model.

Any ideas as to why this would happen?

**Comment by kentcdodds** [comment]
Hmmm... Not sure why that would happen. It would help to see an example. The best way to get help with angular-formly questions like this is to follow the instructions here: http://help.angular-formly.com.

Because the github issues of this repo are reserved for bug reports and feature requests, I'm going to go ahead and close this one. Please follow the instructions indicated above and hopefully we can figure out what's going on. Thanks for using angular-formly!

**Comment by BartVDACodeware** [comment]
This is because of the nature of Breeze.
Breeze entities has a object 'entityAspect' on every entity.
'entityAspect' is used to keep track on changes, etc.
Also every entityAspect is pointing to his own entity also, causing a circular reference.
I have added a suggestion to breezejs to change the name entityAspect to $entityAspect.
this will skip AngularJS.equal function to compare this property

please vote here:
https://breezejs.uservoice.com/forums/173093-1-breezejs-feature-suggestions/suggestions/9073255-change-entityaspect-name-to-entityaspect-to-preve

**Comment by kentcdodds** [comment]
Thanks for the FYI @BartVDACodeware!

**Comment by BartVDACodeware** [comment]
@kentcdodds can you have a look at the discussion at breeze (https://breezejs.uservoice.com/forums/173093-1-breezejs-feature-suggestions/suggestions/9073255-change-entityaspect-name-to-entityaspect-to-preve)?

Ward is asking why the watch approach is used.
Thanks

**Comment by kentcdodds** [comment]
Done

**Comment by benoror** [comment]
Hey @BartVDACodeware !

That happened to this in the end? This you find a workaround?

I think I'm havind a similar issue with another **Tree** project: https://github.com/ceolter/ag-grid/issues/533

**Comment by DeBiese** [comment]
Hey @benoror , we ended up dropping formly for our project. 
Not really a solution, just a decision of what we wanted to keep using the most...
