### ISSUE TITLE
multiple columns

### ISSUE THREAD

**Issue by GoNode5** [formly-js/angular-formly#416]
I have this requirement for a form, columns are not repeating but in this case I need 3 columns for input, a divider and again 3 columns... 
![multicolumn](https://cloud.githubusercontent.com/assets/2210672/9058622/dfcb3a06-3aa2-11e5-9195-02eae5ab42c9.jpg)

(why I need this: replacing an old terminal screen, laptopscreens 1366x768 where you have more width,)

**Comment by kentcdodds** [comment]
Hi @GoNode5! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat!
