### ISSUE TITLE
Custom validator not triggered with Angular 1.2 (as they are triggered with Angular 1.4)

### ISSUE THREAD

**Issue by janjonas** [formly-js/angular-formly#442]
We need to use Angular 1.2 to support IE8. As far as I understand formly it supports version 1.2 and takes care of all differences between Angular 1.2 and Angular 1.4 when validating forms.

Unfortunately, I've problems to set up formly custom validators with Angular 1.2. I've created a JSBin http://jsbin.com/bojamerizu/edit?html,js,console,output to demonstrate the problem. The form contains one field with a custom validator that tests the string length. With Angular 1.4 everything works as expected (just change the include in the HTML): 
* Form is initially invalid
* Clicking on links "Load Valid", "Load Invalid" changes the form's validation state

With Angular 1.2 the validation seems not to be triggered, i.e. the form is always in a valid state. Validation is only triggered when directly changing the inputs, but not when the form's modul is updated.

Do I miss something to support Angular 1.2?

**Comment by kentcdodds** [comment]
Hmmm... When in angular 1.2, angular-formly uses the `$parsers` api to do validation (standard way to do validation in 1.2). I think this is happening because angular 1.2 doesn't re-run the parsers when the model is changed programmatically (as it is in your example). So you're going to have to figure out a way to trigger the parsers to re-run whenever you change the model programmatically. You might consider looking into the `watchers` property to do this.

Let me know if you think there's something that we can do in angular-formly core to make this easier for you and we can talk about it. Otherwise I'm going to close this as a `wont-fix`. Good luck!

**Comment by janjonas** [comment]
I can re-run the parser by calling
{code}vm.editForm.formly_1_input_Name_0.$parsers[0](vm.editForm.formly_1_input_Name_0.$modelValue);{code}
but this does not change the form's validation status. Maybe this SO question is related http://stackoverflow.com/questions/17621171/angularjs-custom-validation-not-firing-when-changing-the-model-programatically?
I'm wondering why there isn't a simple API an the formly form that takes care of the re-validation based on the current model.

**Comment by kentcdodds** [comment]
Hmmm... If you can come up with a consistent way to update the validity properly, then perhaps I can find a good way to integrate that solution into formly core (or I'd happily accept a PR).
