### ISSUE TITLE
Trying to use angular-formly with Angular Material's md-autocomplete

### ISSUE THREAD

**Issue by leandrocosta** [formly-js/angular-formly#469]
Angular Material's <md-autocomplete/> doesn't work with ng-model. Because that angular-formly doesn't create options.formControl and doesn't put required when necessary. What would be the best way to make them work together?

http://jsbin.com/duyobi/edit?html,js,output

**Comment by kentcdodds** [comment]
You might consider creating a custom directive that wraps this one and uses `ng-model`. The problem is, without `ng-model`, then `formControl` wouldn't really make sense. It would technically not be a `formControl`. One thing you might try is to simply add an `ng-model` on it and see what happens... Either way, this particular directive is doing it wrong. They should use `ng-model`. Sorry, I don't think there's anything that angular-formly can do. If you need additional help, please follow the instructions here: http://help.angular-formly.com
