### ISSUE TITLE
Lazy Loading of a form

### ISSUE THREAD

**Issue by Werick** [formly-js/angular-formly#477]
Does formly allow lazy loading of a form that is organized in tabs? We have a form that has about 100 questions and alot of validations in various fields. I've disabled the api check and still it takes about 40-50 seconds to render the form. Is there a way we can lazily load this form so it renders more faster may be in 10-15 seconds by only loading the first tab and load the other tabs when the user clicks on the individual tabs?

**Comment by kentcdodds** [comment]
I recommend that your tabs implementation uses `ng-if` to wait to compile the tab until it's shown. If you need help doing this, please follow the instructions here: http://help.angular-formly.com

Because this repo's github issues are reserved for bug reports and feature requests, I'm going to close this issue. Good luck!
