### ISSUE TITLE
Add a watcher for when hideExpression has a callback function

### ISSUE THREAD

**Issue by jpuzzo** [formly-js/angular-formly#493]
Returning an expression when using a callback function for hideExpression doesn't seem to have an immediate impact on the fields being hidden (or attempting to be).  

My use case is returning a scope variable external to the form which is altered externally as well.

**Comment by kentcdodds** [comment]
Could you please reproduce this issue here? http://issue.angular-formly.com/

**Comment by jpuzzo** [comment]
http://jsbin.com/sotugaxavi/1/edit?html,js,console,output

Sorry to exclude it initially. I had made an example in gitter but it was broken when I went back to it.  Should be fixed now.

Also, if there's a better way to accomplish what I'm trying to do without necessarily addressing the title of the issue, I'd be okay with that too :)

**Comment by kentcdodds** [comment]
Try this instead: http://jsbin.com/bogewe/edit?html,js,output

Because this is more of a question than a bug or a feature request, I'm going to close the issue. Please take this to [the chat](http://chat.angular-formly.com) or [stack overflow](http://question.angular-formly.com/) if you have further questions. Good luck!

**Comment by jpuzzo** [comment]
I dig it. Exactly what I needed since I had a bunch of hideExpressions already in place that were in string format that I needed to tack onto.

I appreciate the speedy response & thank you :+1:

**Comment by kentcdodds** [comment]
Yeah, you definitely want to avoid anything that has to do with `$broadcast` :-)
