### ISSUE TITLE
Cascade Select

### ISSUE THREAD

**Issue by Javammer** [formly-js/angular-formly#502]
Hi, I am using Angular formly-form. I am having difficulty implementing the cascade select dropdown menus. My team uses a json file outside the js file to define the fields. So, I can't define the function for controller inside the json file for watching the field. Please see below are the fields from the JSON file. Field2 has to populate on the event of field1 change. Any help is greatly appreciated 

 {
							"key": "field1",
							"type": "horizontalSelect",
							"templateOptions": {
							  "label": "Fund Number",
							  "valueProp": "value",
							   "required": "true",
							  "options": []
							},
							 "validation": {
					          "show":false
					        },
					        "expressionProperties": {
					          "validation.show":"model.showErrorState === true ? true : null"
					        }
						  },
						  {
							"key": "field2",
							"type": "horizontalSelect",
							"templateOptions": {
							  "label": "Fund Name",
							   "options": "[]"
							},
							"expressionProperties": { 
							 "templateOptions.disabled": "!model.field1"
							  
					        }
						  },

**Comment by benoror** [comment]
Hi @Javammer, Thanks for your interest in angular-formly. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
