### ISSUE TITLE
fieldObject, listen to form "submitted"

### ISSUE THREAD

**Issue by Luddinus** [formly-js/angular-formly#505]
Hi.

Is there a way to listen from a field to main form subbmited?

I want to "format" the field model before data is sent to the server.

Maybe is a better way to do what I want, but this is what I'm thinking, something like this:

```
// fieldController
$scope.$on('formIsSubmitted', function() {
   // field model value
   $scope.model[$scope.name] = ValueFormatted;
});
```

thx.

**Comment by benoror** [comment]
Hi @Luddinus ! Thanks for your interest in angular-formly. I'm sure that angular already do this. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by benoror** [comment]
@Luddinus you can pass a function to the form with `ng-submit`, and do some pre-processing there (before hitting the backend):

      <form ng-submit="vm.onSubmit()" name="vm.form" novalidate>
        <formly-form model="vm.model" fields="vm.fields" options="vm.options" form="vm.form">
          
        </formly-form>
      </form>

More info: https://docs.angularjs.org/api/ng/directive/ngSubmit

**Comment by Luddinus** [comment]
@benoror The things is that I'm making a custom component and I'd like to automatize that process always. I'll check that link.

Thx!
