### ISSUE TITLE
Advanced Layout Bootstrap - wrapping formGroup with custom layout

### ISSUE THREAD

**Issue by eliagentili** [formly-js/angular-formly#508]
Hi,
i've been playing a lot with formly trying to obtain an advanced layout like this one

![Screenshot of Complex Form](http://s15.postimg.org/6ybokbsbf/Faldi_Motors.jpg)

Unfortunately I didn't succeed. The only workaround i've found was to create a custom input template, like in the "nested form" example (http://angular-formly.com/#/example/other/nested-formly-forms), but the problem here is that i need to change my model data wrapping all the fields that i want in a new panel with an index key refers to custom template.

Is there any other way to obtain that?

Thanks

**Comment by benoror** [comment]
Hi @eliagentili! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by benoror** [comment]
@eliagentili did you try using several `<formly-form>` tags in your template?
