### ISSUE TITLE
7.2.0 is no longer a one-step install using bower (no dist/ directory).

### ISSUE THREAD

**Issue by joshuarh** [formly-js/angular-formly#509]
Not sure if I'm missing something here, but ..

When installing formly via bower using `bower install angular-formly`, it doesn't work because the mainfile is listed as `dist/formly.js` which doesn't exist.

I don't see it in the repository either, though it is there in `7.1.x` versions.

Is this intentional and if so, is there a recommended way to install via `bower`?

**Comment by kentcdodds** [comment]
It's not available in the repository. We're using [`publish-latest`](http://npm.im/publish-latest) which pushes the releases to [the `latest` branch](https://github.com/formly-js/angular-formly/tree/latest) ([more info](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564)).

In any case, `publish-latest` had a problem and that's why the last release didn't work out. This has been resolved and a new release is being published as we speak :-)

**Comment by joshuarh** [comment]
Works great now @kentcdodds, thanks!
