### ISSUE TITLE
formly-field's fc array doens't work with validation

### ISSUE THREAD

**Issue by yushkovskiy** [formly-js/angular-formly#510]
https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L324
From this line we can see that formControl can be an array. And right after that function addShowMessagesWatcher() is invoked. Inside this function we can find the condition
if (!fc.$invalid) which will be always resolved to true, because fc is array. This means that this watch will never work.

**Comment by kentcdodds** [comment]
This should be relatively easy to fix. Mind submitting a PR?

**Comment by yushkovskiy** [comment]
Sorry I'm not sure what you mean by PR. I guess it is problem reproduce or something
http://jsbin.com/leroci/edit?js,output

**Comment by kentcdodds** [comment]
Sorry, by PR I meant [Pull Request](https://help.github.com/articles/using-pull-requests/). Occasionally I'll reserve issues for [first timers only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) would you like me to reserve this one for you and help you know what to do?

**Comment by chrisheninger** [comment]
Hi @kentcdodds,

I’ve been keeping an eye out for an issue that is first-timer compatible– if this is up-for-grabs I’d love to take a shot!

I watched the Submitting a Pull Request video, set up the codebase, and read through formly-field.js. I don’t fully understand what is happening in yushkovskiy’s example, but I do think I understand the premise of the bug.

Could you help me write the proper tests and point me in the correct direction for implementing a fix? Thanks!

**Comment by kentcdodds** [comment]
Awesome! I love the initiative! I'll get a test written for you as soon as possible (probably tomorrow hopefully)

**Comment by kentcdodds** [comment]
Hey @chrisheninger! Have at it! Here are [the tests](https://github.com/formly-js/angular-formly/blob/3bba183835c91866c5a1377f64fe31a3006038bd/src/directives/formly-field.test.js#L1324-L1356).

[This line](https://github.com/formly-js/angular-formly/blob/3bba183835c91866c5a1377f64fe31a3006038bd/src/directives/formly-field.js#L343) and [this line](https://github.com/formly-js/angular-formly/blob/3bba183835c91866c5a1377f64fe31a3006038bd/src/directives/formly-field.js#L351) need to take an array of `scope.fc`s into account. I recommend you utilize the `arrayify` method (which you have access to in the scope of that function) which will take an argument and convert it to an array if it's not already one. Then call something like this on it: `.some(f => f.$invalid);` (or `$touched` for the other case).

One thing I just realized my test case doesn't cover is [this line](https://github.com/formly-js/angular-formly/blob/3bba183835c91866c5a1377f64fe31a3006038bd/src/directives/formly-field.js#L350) and [this line](https://github.com/formly-js/angular-formly/blob/3bba183835c91866c5a1377f64fe31a3006038bd/src/directives/formly-field.js#L348). If you want to take a whack at writing tests for those scenarios too that'd be cool, otherwise let me know and I'll write up tests for those next time I get a chance. Good luck!!!

**Comment by kentcdodds** [comment]
I've added a few more tests, but it still doesn't cover everything. I'll be honest, this one's a bit more complex. Don't feel bad if you have a hard time with the implementation.

**Comment by chrisheninger** [comment]
Thanks @kentcdodds! I think I figured out the initial solution. If I did the first part correctly, I’d like to take a look into figuring out the next two pieces– I do however need assistance writing the tests!

[First line change](https://github.com/chrisheninger/angular-formly/blob/master/src/directives/formly-field.js#L343)
[Second line change](https://github.com/chrisheninger/angular-formly/blob/master/src/directives/formly-field.js#L351)

That was my first time using the `some` method as well as an arrow function… quite the learning experience!

A couple of questions: 
On the second line, we were using `scope.fc` previously and I changed it to use `fc` for consistency with the pieces above. Those are referencing the same object, correct?

I messed up my commit and had to commit twice (first time I forgot to uncomment the .skip on the test)… doesn’t that affect anything on your end negatively? I was also a bit unsure about the commit message/title for this issue, would appreciate input. I can easily fork and commit again!

Would it be best to submit a PR now, or should I wait until we take a look at the next part?

Thanks again! Learning immensely from seeing the process and tinkering through all the code. 😀

**Comment by kentcdodds** [comment]
Let's hold on the PR  now and get this all done in one. I'll give your commits a closer look tomorrow. I'm glad this is a learning experience for you! That's the point :-)

**Comment by kentcdodds** [comment]
Just looked at your implementation. Do fast, so good :+1:

**Comment by kentcdodds** [comment]
Sorry, autocorrect... I'm meant "So far, so good"

**Comment by chrisheninger** [comment]
Hey Kent, I noticed you had updated the tests. Do those cover the next two lines you had referenced in your previous message? I noticed there's a special event happening today/tomorrow, would be glad to give this a whirl during the bash! Any advice you have to point me in the right direction would help!

**Comment by kentcdodds** [comment]
The tests don't cover everything that needs to be covered. I'll try to get the remaining test or two written. But basically anything in that function that references `scope.fc` needs to handle situations where `scope.fc` is an array.

**Comment by bjspencer** [comment]
Hey @chrisheninger, nice work finding this and working on it. I ran into this same issue, so I picked up your fork and tied off a few loose ends. I've got a pull request in right now that I think should be good.

**Comment by chrisheninger** [comment]
@bjspencer awesome, I'm excited to see the implementation!

I made a minor mistake in the way I merged from upstream into my fork– after chatting @kentcdodds I learned it should've been executed using rebase. I'd recommend grabbing a clean fork so you don't have all my ugly commits in your PR... I won't be offended!

**Comment by bjspencer** [comment]
Alright, I had some difficulties getting the tests to run on my machine locally, but I've gotten that all straightened out. I'm pretty sure that the implementation is good, but the formerly skipped test on formly-src/directives/field.tests.js:1393 fails. Unfortunately, I don't understand the tests very well, and I'm at my limit on how much time I can spend on this right now, so I'll need some additional help.

That being said, I was able to enable the test at src/directives/formly-field.test.js:1369 and it runs successfully, and the method works for the cases that I ran into where it was problematic. Per recommendation by @chrisheninger, I made my own fork directly off of angular-formly at https://github.com/bjspencer/angular-formly.

**Comment by kentcdodds** [comment]
Looks pretty solid. I'll need to get to a computer to work out helping with that last test. Thank you very much!

**Comment by kentcdodds** [comment]
@bjspencer, looking at your solution I think that it's better than what I was planning on. So you'll want to change the test that you have skipped. Instead of

```javascript
expect(spy).to.have.been.calledWith(sinon.match.array, sinon.match.array)
```

Do:

```javascript
expect(spy).to.have.been.calledTwice // once for each form control.
```

That should do it :-) Then make a PR and I'll merge it :D

**Comment by kentcdodds** [comment]
@bjspencer's PR #553 just got merged. A new release will be pushed out automatically in a few moments :+1:

**Comment by kentcdodds** [comment]
Please try it out and report back if it's not behaving as you expect. Until then, I'm closing this. Thanks @bjspencer and @chrisheninger!

**Comment by hrgui** [comment]
@kentcdodds @bjspencer @chrisheninger 

Any suggestions on how `formlyConfig.extras.errorExistsAndShouldBeVisibleExpression` should work? Now that fc could be an array, doing the following expression won't work:

`fc.$error && (fc.$dirty || form.$submitted);`

It's because fc is an array, and fc will never have $error and $dirty. The work around I have is currently the following:

`(fc.$error || fc[0].$error) && (fc.$dirty || fc[0].$dirty || form.$submitted);`


One potential solution that I could think of is we could potentially gather all the variables of fc and join them to 1 single variable to designate whether the error should show or not.

**Comment by kentcdodds** [comment]
Have you tried providing a function to `errorExistsAndShouldBeVisibleExpression` rather than simply a string? :-)

**Comment by hrgui** [comment]
Just found that out right now. :+1: That's much better than a string.

**Comment by hrgui** [comment]
@kentcdodds , that did work but now I run to another problem: 
````html
<div ng-messages ng-if="options.validation.errorExistsAndShouldBeVisible"
                               ng-messages="options.formControl.$error">
    <div ng-message-exp="::name"
            ng-repeat="(name, message) in ::options.validation.messages">
      {{message(options.formControl.$viewValue, options.formControl.$modelValue, this)}}
    </div>
  </div>
````

The problem lies within here: `ng-messages="options.formControl.$error"`.

One current workaround I have is: `ng-messages="fc.$error || fc[0].$error` , but that's probably not going to work so well. Any ideas?

**Comment by kentcdodds** [comment]
I think that really depends on your use case. For example, what do you want to have it do when two of the fields have `required` in their `$error`? Show two? Show one? Either way, I think you might be able to have a function you call to get the `$error` object rather than simply referencing it there... Just really depends on your specific use case I think.
