### ISSUE TITLE
[documentation] How exactly should I go about using a directive with a formly type?

### ISSUE THREAD

**Issue by cfv1984** [formly-js/angular-formly#515]
Hi! I just noticed there is no explanation of a "right" way to do this, even if it is mentioned this is possible. 

I've managed to shoehorn my own directives into the code, and am not sure I'm doing it the "right" way since there doesn't seem to be a canonical "right" way on display anywhere. 

Is this something that exists, or should I put up a couple examples of how I did it instead?

**Comment by kentcdodds** [comment]
There are plenty of examples on the website that demonstrate using angular-formly with a custom directive. The best example is probably the [UI-Datepicker](http://angular-formly.com/#/example/integrations/ui-datepicker) one.

I'm going to close this because the github issues are reserved for bug reports and feature requests. If you have further questions or need help, follow the instructions at http://help.angular-formly.com
