### ISSUE TITLE
OnChange and validators

### ISSUE THREAD

**Issue by Darex1991** [formly-js/angular-formly#526]
Hi, I want to get value of input. But when I used validators I got value only when this value is correctly ;/
Any ideas?
```
validators:
          urlAddress:
            expression: (viewValue, modelValue) =>
              if (@fieldActive['section_name'] || @fieldActive['detail_id'] || @file)
                true
              else
                value = viewValue || modelValue
                @importUrlRegexService.importUrlValidator(value)
            message: '$viewValue + " is not a valid URL Address"'

templateOptions:
    onChange: (newValue, oldValue, scope) =>
        value = newValue || oldValue
        console.log value       <= give me value only when it's pass```

**Comment by kentcdodds** [comment]
If you take a look at how `onChange` is called, you'll see why you're experiencing this. It's called with: `model[options.key], options, this, $event` which is roughly equivalent to: `$modelValue, options, scope, $event`. If you want the `$viewValue`, then you can get it from `scope.fc.$viewValue`.

I'm going to close this issue because issues on this repo are reserved for big reports and feature requests. If you need more help, go to http://help.angular-formly.com

Also, what language is that code you showed? It's not JavaScript and it looks unlike any CoffeeScript I've ever seen...

**Comment by Darex1991** [comment]
It's coffee, but I pasted it with tabs. Tnx for help
