### ISSUE TITLE
On After Formly Rendered

### ISSUE THREAD

**Issue by mickomicko5573** [formly-js/angular-formly#540]
Hi Kent,
 Is there a way to know when formly done render?
 Thanks.

**Comment by kentcdodds** [comment]
There is not. This has been asked for quite a bit. My guess is you want to know when it's done rendering because it's taking a long time to render. Please make sure that you're following the [production tips](http://angular-formly.com/#/example/other/production-tips) to make sure that you disable some of the developer related things which should speed things up quite a bit for you. After that, you'll just have to make sure that your design is conducive to a performant form.

**Comment by mickomicko5573** [comment]
Thanks.

**Comment by computerex** [comment]
We need this callback because we need to initialize some state after the DOM is rendered. Currently we have to resort to using $timeout hack. Any plans to add this in the future?

**Comment by kentcdodds** [comment]
No plans, sorry
