### ISSUE TITLE
Access $invalid function from the controller

### ISSUE THREAD

**Issue by asaf050** [formly-js/angular-formly#554]
Hey,
I am looking for a way to access the $invalid function..

How can I do it?

Thanks
Asaf

**Comment by benoror** [comment]
Hi @asaf050! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
