### ISSUE TITLE
Field hidden with hideExpression unaccessible after being shown

### ISSUE THREAD

**Issue by zorzysty** [formly-js/angular-formly#555]
I've got a field which must be hidden until a REST response says otherwise.
That's the code I use:
```
id: "nameInput",
hideExpression: function () {
  return !vm.model.nameRequired
}
```
On recieving certain REST response,  (1.) the field must be shown, (2.) set to required and (3.) required validation ng-message must be displayed.

Here's my code:

**In field description:**
```
expressionProperties: {
    "templateOptions.required": function () {
        return vm.model.nameRequired
    }
}
```
**After REST promise is resolved:**
```
vm.model.nameRequired = true;
vm.form.nameInput.$setTouched();
```

The problem is that ```vm.form.nameInput``` is undefined at this point.

How can I invoke $setTouched() after the field is instantiated and it's object accessible?

**EDIT:**
It works when I wrap it with $timeout:
```
vm.model.nameRequired = true;
$timeout(function () {
    vm.form.nameInput.$setTouched();
});
```
But that's pretty ugly hack and doesn't work well with Protractor E2E tests.

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!
