### ISSUE TITLE
Nested Property Keys not working multi-checkbox

### ISSUE THREAD

**Issue by Werick** [formly-js/angular-formly#561]
Hi,
Am using nested properties for my keys how ever the multiCheckbox seems not to be working. See this example http://jsbin.com/saripusono/edit?html,js,output.
Thanks
Erick

**Comment by epnikolop** [comment]
Not an issue please try that
```javascript
    vm.model = {
      even: {
        with:{}
      }
    };
```
and
```javascript   
{
        key: 'arrays',
        type: 'multiCheckbox',
        model: vm.model.even.with,
        templateOptions: {
          label: 'Array property',
          options:[{value:'test',name:'test'},{value:'test1',name:'test1'}]
       }
}
```

**Comment by benoror** [comment]
I'm going to go ahead and close this issue.

**Comment by epnikolop** [comment]
This should be reopened as i typed incorrectly above that is not an issue i'm new in formly and I wasn't aware of the nested functionality that other type of field types correctly support, my comment above it's just a by-pass of the issue.

**Comment by benoror** [comment]
I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
