### ISSUE TITLE
It is possible to to submit the form (not using the model) ?

### ISSUE THREAD

**Issue by monkeymonk** [formly-js/angular-formly#564]
I can do the "regular" submit using :

```html
<form method="post" action="#wathever" name="vm.form" novalidate>
    <formly-form model="vm.model" options="vm.options" form="vm.form" fields="vm.fields">
                <button class="btn btn-info" type="submit">Send</button>
    </formly-form>
</form>
```

But, the data sent are not correct, eg:

```
"formly_form_horizontalInput_street_0" => "somewhere"
"formly_form_horizontalInput_postal_1" => "45910"
"formly_form_horizontalInput_city_2" => "Over the rainbow"
```

which should be :

```
"street" => "somewhere"
"postal" => "45910"
"city" => "Over the rainbow"
```

How can I send the correct data via "regular" submit (not AJAX powered) ?

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!
