### ISSUE TITLE
cascaded inputs

### ISSUE THREAD

**Issue by bondarewicz** [formly-js/angular-formly#568]
Based on [cascaded select](http://angular-formly.com/#/example/other/cascaded-select) example, would it be possible to turn this into "cascaded input" ? 
Imagine 1 select on page, then:

- selecting 1st option would result in 2nd input being created as select (with options)
- selecting 2nd option would result in 2nd input being created as input (freetype)
- selecting 3rd option would result in 2nd input being created as checkbox (true/false)

It would be awesome to have that as an example...

**Comment by benoror** [comment]
Hi @bondarewicz! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

Also, do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
