### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by david-nelson-moscow** [formly-js/angular-formly#571]
Any thought or timeline to migrate to Angular 2?

**Comment by kentcdodds** [comment]
Hi @david-nelson-moscow, I don't personally have any plans to work on an Angular 2 version of angular-formly. That (of course) does not preclude anyone else from working on it.

Originally I had planned on making an Angular 2 version of angular-formly. However with so many things competing for my time, I can't justify spending time on it. I was able to justify working on angular-formly before because I was using it at work and I used Angular heavily. But I will soon be changing jobs and will be using React. So I no longer have a use case for angular-formly.

Perhaps someone on the @formly-js/angular-formly-collaborators or @formly-js/angular-formly-collaborators-read team will be up to the challenge.

Thanks for asking!
