### ISSUE TITLE
Color picker and file fild

### ISSUE THREAD

**Issue by tiagocedrim** [formly-js/angular-formly#576]
How do I have fields of type file and color picker?

**Comment by benoror** [comment]
Hi @tiagocedrim! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by benoror** [comment]
You can set `type` attribute to [default input templates](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/input.js) this way:

```
    defaultOptions: {
      templateOptions: {
        type: 'file'
      }
    }
```

```
    defaultOptions: {
      templateOptions: {
        type: 'color'
      }
    }
```

For more information on HTML Input Types see: http://www.w3schools.com/htmL/html_form_input_types.asp
