### ISSUE TITLE
model value cannot be refreshed in formlyConfigProvider.setType controller

### ISSUE THREAD

**Issue by TonyLuo** [formly-js/angular-formly#596]
I tried to show the preview for the image using ormlyConfigProvider.setType, but it seems the model value sometimes will refer to the previous one. Is something wrong with my code?

```
formlyConfigProvider.setType({
        name: 'qiniu-single-img',
        templateUrl: 'scripts/components/common/formly-types/elements/qiniu-single-img.html',
        controller: function ($scope, $log, $qupload, AppConstant) {
            $scope.modelValue = $scope.model[$scope.options.key];
```
qiniu-single-img.html
```
        <div class="image"><img data-ng-src="{{modelValue}}"  style="width: 50px;"/></div>
```

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!
