### ISSUE TITLE
Multiple inputs within a formly template

### ISSUE THREAD

**Issue by kurokoda** [formly-js/angular-formly#597]
What would be the best way of implementing a single Formly template which contained multiple input fields, each tied to a different property of the model, e.g. an input field with a related dropdown field beside it?

<img width="267" alt="screen shot 2016-01-07 at 6 59 43 pm" src="https://cloud.githubusercontent.com/assets/5505136/12186452/fcde09ea-b570-11e5-86bd-e0a990f56ef8.png">

I've tried:

```javascript
<div class="grid-form grid-row dual-input">
  <input ng-model="model[{{options.data.inputModel}}]" type="text" name="foo">
  <select
    name="units"
    ng-model="model[{{options.data.dropdownModel}}]"
    ng-options="option.id as option.display for option in options.data.options">
    <option value="" selected>units</option>
  </select>
</div>
```

But of course, the dot syntax in the brackets breaks.

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!

**Comment by abodacs** [comment]
@kurokoda has you get  a solution?
