### ISSUE TITLE
Disable first item in Select and Add one additional item.

### ISSUE THREAD

**Issue by hardikkaji** [formly-js/angular-formly#598]
I am trying to disable first Item in select box. I have not find any documents for it.

Please help me for this.

**Comment by benoror** [comment]
Hi @hardikkaji! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by benoror** [comment]
@hardikkaji take a look at: http://www.w3schools.com/tags/att_select_disabled.asp
