### ISSUE TITLE
validation not accept number

### ISSUE THREAD

**Issue by pequenopadre** [formly-js/angular-formly#608]
good Morning!
excuse my lack of knowledge , I am new to the angular - formly and I wonder how and where should I create a validation for the input did not accept the input numbers.
sorry the English using google translator
{
      "className": "col-md-7 ",
      "type": "input",
      "key": "Nome",
      "templateOptions": {
        "required": true,
        "type": "text",
        "label": "Nome",
        "maxlength": 100
      }
    }

**Comment by benoror** [comment]
Hi @pequenopadre! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by benoror** [comment]
# Simple solution

HTML5 Input Types

- http://www.w3schools.com/tags/att_input_type.asp
- http://www.w3schools.com/html/html_form_input_types.asp

# Formly solution

Custom validators

- https://egghead.io/lessons/angularjs-angular-formly-custom-validation?pl=7
- http://docs.angular-formly.com/docs/validation
- http://angular-formly.com/#/example/advanced/validators
- http://docs.angular-formly.com/docs/formly-custom-validation
