### ISSUE TITLE
Trying to $compile form results in form with no fields

### ISSUE THREAD

**Issue by Flascher** [formly-js/angular-formly#620]
Hi there,

I'm currently trying to implement a modal that can automatically generate a formly-form for you when you pass it your formly-fields. 

I've made a codepen showing my issue here: http://codepen.io/Flascher/pen/vLjjYV

Please ignore the use of jQuery UI... unfortunately I can't do anything about that :(

**Comment by benoror** [comment]
Hi @Flascher! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
