### ISSUE TITLE
UI datepicker multiple pattern (format)?

### ISSUE THREAD

**Issue by Markoo08** [formly-js/angular-formly#621]
Hello, is possible to validate user date input on multiple patterns (formats)? i dont see any example

**Comment by benoror** [comment]
Hi @Markoo08! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!
