### ISSUE TITLE
[feature request?] Default value for checkbox

### ISSUE THREAD

**Issue by xphong** [formly-js/angular-formly#686]
There doesn't seem to be a defaultValue option for checkboxes (unless there is)

This doesn't work: 
```
            {
              "templateOptions": {
                "label": "My checkbox",
                "required": false
              },
              "key": "checkboxKey",
              "type": "checkbox",
              "defaultValue": true
            }

```
Currently, I resorted to using: 
```
            {
              "templateOptions": {
                "label": "My checkbox",
                "required": false
              },
              "ngModelElAttrs": {
                "ng-init": "model.checkboxKey=true"
              },
              "key": "checkboxKey",
              "type": "checkbox"
            }
```

**Comment by kentcdodds** [comment]
Hi @xphong, I'm not seeing the same thing you are. You can see it working here: https://jsbin.com/bivoxoz/edit?html,js,output

Could you please reproduce your issue using [issue.angular-formly.com](http://issue.angular-formly.com/)? It will help us determine what exactly the problem is that you're describing and how it could be fixed. Thanks!

**Comment by xphong** [comment]
Thanks for the quick reponse @kentcdodds .

I found out that the defaultValue wasn't working because of my custom template that uses Angular Material.

I had to add 

`ng-class="{ 'md-checked': model[options.key] }" `

to
```
    <md-checkbox ng-model="model[options.key]" ng-class="{ 'md-checked': model[options.key] }" class="md-primary dh-md-checkbox">
        {{to.label}}
    </md-checkbox>
```
